import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname } from "path";
import type { Graph } from "./types";
import type { GraphNode } from "../adapters/types";
import { DOMAINS, keywordClassify, defaultRuleDomainsPath, loadRuleDomains } from "./builder";
import { inference } from "../adapters/inference";

export interface AutoDomainResult {
  classified: number;
  skipped: number;
  total: number;
  entries: Array<{ nodeId: string; domains: string[]; method: "keyword" | "ai" }>;
  errors: string[];
}

interface RuleDomainEntry {
  domains: string[];
  source: string;
}

interface RuleDomainsFile {
  version: number;
  reviewed: boolean;
  rules: Record<string, RuleDomainEntry>;
}

export interface AutoDomainOptions {
  ruleDomainsPath?: string;
  maxNodes?: number;
  dryRun?: boolean;
}

const CLASSIFY_SYSTEM = `You are a behavioral rule classifier. Given a rule, assign 1-2 domain tags.
Available domains: ${DOMAINS.join(", ")}
Respond with JSON only: {"domains": ["tag1"]}`;

function needsClassification(
  node: GraphNode,
  existing: RuleDomainsFile | null,
): boolean {
  // Check rule-domains.json entry
  const entry = existing?.rules[node.id];
  if (entry) {
    // Never touch reviewed entries
    if (entry.source === "reviewed") return false;
    // Already auto-classified — idempotent skip
    if (entry.source === "auto") return false;
    // Keyword-sourced entries get re-classified for higher quality
    if (entry.source === "keyword") return true;
  }

  // Node has no domains at all
  if (node.domains.length === 0) return true;

  // Node has keyword-sourced domains — upgrade
  if (node.domainSource === "keyword") return true;

  // Node has domains from other sources (ai, propagation, override) — skip
  return false;
}

async function classifyNode(
  node: GraphNode,
): Promise<{ domains: string[]; method: "keyword" | "ai" } | null> {
  const text = node.description || node.name;
  const name = node.name || node.id;

  // Try keyword classification first (free, no LLM call)
  const keywordDomains = keywordClassify(name, text, text);
  if (keywordDomains && keywordDomains.length > 0) {
    return { domains: keywordDomains, method: "keyword" };
  }

  // Fall back to LLM
  try {
    const res = await inference({
      systemPrompt: CLASSIFY_SYSTEM,
      userPrompt: `Rule: ${text.slice(0, 500)}`,
      level: "fast",
      expectJson: true,
      timeout: 15_000,
    });

    if (res.success && res.parsed) {
      const parsed = res.parsed as { domains?: string[] };
      const valid = (parsed.domains || []).filter(
        (d: string) => (DOMAINS as readonly string[]).includes(d),
      );
      if (valid.length > 0) {
        return { domains: valid, method: "ai" };
      }
    }
  } catch {
    // LLM unavailable — skip silently
  }

  return null;
}

/**
 * Auto-generate rule-domains.json entries for nodes missing domain classification.
 *
 * Idempotent: re-running does not re-classify nodes already marked `source: "auto"` or `source: "reviewed"`.
 * Uses keyword classification first, falls back to LLM for ambiguous rules.
 * Caps at maxNodes per run to avoid LLM rate limits.
 */
export async function autoGenerateDomains(
  graph: Graph,
  opts?: AutoDomainOptions,
): Promise<AutoDomainResult> {
  const maxNodes = opts?.maxNodes ?? 50;
  const rdPath = opts?.ruleDomainsPath ?? defaultRuleDomainsPath();
  const dryRun = opts?.dryRun ?? false;

  const result: AutoDomainResult = {
    classified: 0,
    skipped: 0,
    total: Object.keys(graph.nodes).length,
    entries: [],
    errors: [],
  };

  // Load existing rule-domains.json (null if missing)
  const existing = loadRuleDomains(rdPath);

  // Build working copy of rules
  const rules: Record<string, RuleDomainEntry> = existing?.rules
    ? { ...existing.rules }
    : {};

  // Find nodes needing classification
  const candidates: GraphNode[] = [];
  for (const node of Object.values(graph.nodes)) {
    if (needsClassification(node, existing)) {
      candidates.push(node);
    } else {
      result.skipped++;
    }
  }

  // Cap at maxNodes
  const batch = candidates.slice(0, maxNodes);

  // Classify each node
  for (const node of batch) {
    const classification = await classifyNode(node);
    if (classification) {
      rules[node.id] = {
        domains: classification.domains,
        source: "auto",
      };
      result.classified++;
      result.entries.push({
        nodeId: node.id,
        domains: classification.domains,
        method: classification.method,
      });
    }
  }

  // Write results
  if (!dryRun && result.classified > 0) {
    const output: RuleDomainsFile = {
      version: existing?.version ?? 1,
      reviewed: existing?.reviewed ?? false,
      rules,
    };
    const dir = dirname(rdPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(rdPath, JSON.stringify(output, null, 2) + "\n", "utf-8");
  }

  return result;
}

/**
 * Check whether auto-domain generation should run.
 * Returns true if rule-domains.json is missing or has fewer entries than 50% of graph nodes.
 */
export function shouldAutoGenerate(graph: Graph, ruleDomainsPath?: string): boolean {
  const rdPath = ruleDomainsPath ?? defaultRuleDomainsPath();
  const existing = loadRuleDomains(rdPath);

  if (!existing) return true;

  const entryCount = Object.keys(existing.rules).length;
  const nodeCount = Object.keys(graph.nodes).length;

  // Stale: fewer entries than 50% of nodes
  return entryCount < nodeCount * 0.5;
}
