import { describe, test, expect, mock, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, writeFileSync, readFileSync, existsSync, mkdirSync, rmSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import type { GraphNode } from "../../src/adapters/types";
import type { Graph } from "../../src/graph/types";
import { DOMAINS } from "../../src/graph/builder";

function makeNode(id: string, domains: string[], overrides?: Partial<GraphNode>): GraphNode {
  return {
    id,
    file: `${id}.md`,
    type: "rule",
    name: id.replace(/_/g, "-"),
    description: `Description for ${id}`,
    domains,
    severity: 3,
    occurrence_count: 0,
    last_updated: new Date().toISOString(),
    content_hash: "abc",
    memoryType: "behavioral-rule",
    ...overrides,
  };
}

function makeGraph(nodes: Record<string, GraphNode>, edges: Graph["edges"] = []): Graph {
  return {
    version: "1.0",
    builtAt: new Date().toISOString(),
    nodeCount: Object.keys(nodes).length,
    edgeCount: edges.length,
    nodes,
    edges,
  };
}

function makeRuleDomainsFile(rules: Record<string, { domains: string[]; source: string }>): string {
  return JSON.stringify({ version: 1, reviewed: false, rules }, null, 2);
}

// Mock inference to return predictable domains
const mockInference = mock(() =>
  Promise.resolve({
    success: true,
    output: '{"domains": ["verification"]}',
    parsed: { domains: ["verification"] },
    latencyMs: 100,
    level: "fast" as const,
    provider: "claude" as const,
  }),
);

mock.module("../../src/adapters/inference", () => ({
  inference: mockInference,
}));

describe("autoGenerateDomains", () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "auto-domains-test-"));
    mockInference.mockClear();
    mockInference.mockImplementation(() =>
      Promise.resolve({
        success: true,
        output: '{"domains": ["verification"]}',
        parsed: { domains: ["verification"] },
        latencyMs: 100,
        level: "fast" as const,
        provider: "claude" as const,
      }),
    );
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  test("creates rule-domains.json when missing", async () => {
    const { autoGenerateDomains } = await import("../../src/graph/auto-domains");

    const nodes: Record<string, GraphNode> = {
      rule_a: makeNode("rule_a", []),
      rule_b: makeNode("rule_b", ["verification"]),
    };
    const graph = makeGraph(nodes);
    const rdPath = join(tempDir, "rule-domains.json");

    const result = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 50 });

    expect(result.classified).toBeGreaterThanOrEqual(1);
    expect(existsSync(rdPath)).toBe(true);

    const written = JSON.parse(readFileSync(rdPath, "utf-8"));
    expect(written.version).toBe(1);
    expect(Object.keys(written.rules).length).toBeGreaterThanOrEqual(1);
  });

  test("preserves existing source:reviewed entries", async () => {
    const { autoGenerateDomains } = await import("../../src/graph/auto-domains");

    const rdPath = join(tempDir, "rule-domains.json");
    writeFileSync(rdPath, makeRuleDomainsFile({
      reviewed_rule: { domains: ["security"], source: "reviewed" },
    }));

    const nodes: Record<string, GraphNode> = {
      reviewed_rule: makeNode("reviewed_rule", ["security"]),
      unclassified: makeNode("unclassified", []),
    };
    const graph = makeGraph(nodes);

    const result = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 50 });

    const written = JSON.parse(readFileSync(rdPath, "utf-8"));
    expect(written.rules.reviewed_rule.source).toBe("reviewed");
    expect(written.rules.reviewed_rule.domains).toEqual(["security"]);
  });

  test("is idempotent — does not re-classify source:auto nodes", async () => {
    const { autoGenerateDomains } = await import("../../src/graph/auto-domains");

    const rdPath = join(tempDir, "rule-domains.json");
    writeFileSync(rdPath, makeRuleDomainsFile({
      already_done: { domains: ["scope"], source: "auto" },
    }));

    const nodes: Record<string, GraphNode> = {
      already_done: makeNode("already_done", ["scope"]),
    };
    const graph = makeGraph(nodes);

    const result = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 50 });

    expect(result.classified).toBe(0);
    expect(result.skipped).toBeGreaterThanOrEqual(1);
  });

  test("caps at maxNodes", async () => {
    const { autoGenerateDomains } = await import("../../src/graph/auto-domains");

    const nodes: Record<string, GraphNode> = {};
    for (let i = 0; i < 10; i++) {
      nodes[`rule_${i}`] = makeNode(`rule_${i}`, []);
    }
    const graph = makeGraph(nodes);
    const rdPath = join(tempDir, "rule-domains.json");

    const result = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 3 });

    expect(result.classified).toBeLessThanOrEqual(3);
  });

  test("uses keyword classification before LLM", async () => {
    const { autoGenerateDomains } = await import("../../src/graph/auto-domains");

    // Node with keyword-detectable content
    const nodes: Record<string, GraphNode> = {
      deploy_rule: makeNode("deploy_rule", [], {
        description: "make rebuild deploy sequence docker container",
      }),
    };
    const graph = makeGraph(nodes);
    const rdPath = join(tempDir, "rule-domains.json");

    const result = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 50 });

    expect(result.classified).toBe(1);
    // keyword classification should have caught it — no LLM call needed
    expect(mockInference).not.toHaveBeenCalled();

    const written = JSON.parse(readFileSync(rdPath, "utf-8"));
    expect(written.rules.deploy_rule.domains).toContain("deployment");
    expect(written.rules.deploy_rule.source).toBe("auto");
  });

  test("re-classifies nodes with domainSource:keyword via LLM", async () => {
    const { autoGenerateDomains } = await import("../../src/graph/auto-domains");

    const nodes: Record<string, GraphNode> = {
      keyword_node: makeNode("keyword_node", ["scope"], { domainSource: "keyword" }),
    };
    const graph = makeGraph(nodes);
    const rdPath = join(tempDir, "rule-domains.json");
    writeFileSync(rdPath, makeRuleDomainsFile({
      keyword_node: { domains: ["scope"], source: "keyword" },
    }));

    const result = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 50 });

    // Should have attempted LLM classification
    expect(result.classified).toBe(1);
    expect(mockInference).toHaveBeenCalled();
  });

  test("handles inference failure gracefully", async () => {
    const { autoGenerateDomains } = await import("../../src/graph/auto-domains");

    mockInference.mockImplementation(() =>
      Promise.resolve({
        success: false,
        output: "",
        error: "timeout",
        latencyMs: 15000,
        level: "fast" as const,
        provider: "claude" as const,
      }),
    );

    const nodes: Record<string, GraphNode> = {
      ambiguous: makeNode("ambiguous", [], { description: "some ambiguous rule text" }),
    };
    const graph = makeGraph(nodes);
    const rdPath = join(tempDir, "rule-domains.json");

    // Should not throw
    const result = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 50 });

    // keyword might not catch it, LLM fails, so 0 classified
    expect(result.errors.length).toBe(0); // graceful, no errors surfaced
  });

  test("force=true re-classifies source:auto nodes", async () => {
    const { autoGenerateDomains } = await import("../../src/graph/auto-domains");

    const rdPath = join(tempDir, "rule-domains.json");
    writeFileSync(rdPath, makeRuleDomainsFile({
      auto_node: { domains: ["scope"], source: "auto" },
    }));

    const nodes: Record<string, GraphNode> = {
      auto_node: makeNode("auto_node", ["scope"]),
    };
    const graph = makeGraph(nodes);

    // Without force: should skip
    const resultNoForce = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 50, force: false });
    expect(resultNoForce.classified).toBe(0);
    expect(resultNoForce.skipped).toBe(1);

    // With force: should re-classify
    const resultWithForce = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 50, force: true });
    expect(resultWithForce.classified).toBe(1);
    expect(resultWithForce.skipped).toBe(0);
  });

  test("force=true still skips source:reviewed nodes", async () => {
    const { autoGenerateDomains } = await import("../../src/graph/auto-domains");

    const rdPath = join(tempDir, "rule-domains.json");
    writeFileSync(rdPath, makeRuleDomainsFile({
      reviewed_node: { domains: ["security"], source: "reviewed" },
    }));

    const nodes: Record<string, GraphNode> = {
      reviewed_node: makeNode("reviewed_node", ["security"]),
    };
    const graph = makeGraph(nodes);

    const result = await autoGenerateDomains(graph, { ruleDomainsPath: rdPath, maxNodes: 50, force: true });

    expect(result.classified).toBe(0);
    expect(result.skipped).toBe(1);

    const written = JSON.parse(readFileSync(rdPath, "utf-8"));
    expect(written.rules.reviewed_node.source).toBe("reviewed");
    expect(written.rules.reviewed_node.domains).toEqual(["security"]);
  });
});
