#!/usr/bin/env python3
"""Complete domain taxonomy migration — classifies ALL nodes with balanced caps."""

import json
import re
from pathlib import Path
from collections import Counter

KG_PATH = Path.home() / ".agentgrit" / "state" / "knowledge-graph.json"
RD_PATH = Path.home() / ".claude" / "MEMORY" / "LEARNING" / "STATE" / "rule-domains.json"
MAX_PER_DOMAIN = 50

# Explicit classifications for nodes with clear domain affinity
EXPLICIT = {
    # === infra (Docker, containers, Mac Mini, GHCR, ports, daemon, deploy ops) ===
    "feedback_always_use_make_for_mac_mini": "infra",
    "feedback_ask_environment_before_investigating": "infra",
    "feedback_container-environment-first-diagnosis": "infra",
    "feedback_container_fresh_env": "infra",
    "feedback_container_only_architecture": "infra",
    "feedback_da_handle_routine_ops": "infra",
    "feedback_da_runs_rebuild": "infra",
    "feedback_dashboard_build_directory": "infra",
    "feedback_hero_is_l3_no_browser": "infra",
    "feedback_iterative_mac_mini_deploy": "infra",
    "feedback_mac_mini_l4_deployment": "infra",
    "feedback_playwright_project_routing": "infra",
    "feedback_test-container-currency-gate": "infra",
    "feedback_test-container-must-be-current": "infra",
    "feedback_test_before_production": "infra",
    "feedback_test_fresh_container": "infra",
    "feedback_use_makefile_deploy": "infra",
    "feedback_cloud_marketplace_hero_not_mac_mini": "infra",
    "feedback_deep_root_cause_tracing": "infra",
    "feedback_root_cause_multi_layer": "infra",
    "feedback_every_cycle_pattern_is_root_cause": "infra",
    "feedback_verify-install-scripts-not-docs": "infra",
    "feedback_server_restart": "infra",
    "feedback_chmod_hooks_after_write": "infra",
    "feedback_claude_sensitive_file_gate": "infra",
    "feedback_no_session_scheduling": "infra",
    "feedback_post-install-verify-directory-structure": "infra",
    "feedback_no_write_tool_env": "infra",
    "feedback_tableau_no_vpn": "infra",
    "reference_ghcr_credentials": "infra",
    "reference_mac_mini_data_sync": "infra",
    "reference_mac_mini_ssh": "infra",
    "reference_dailybrief_project_path": "infra",
    "project_demo_machine_plan": "infra",
    "project_l4_scraper_container": "infra",
    "project_dailybrief_flow": "infra",
    "project_node_role_architecture": "infra",
    "project_leader_flag_decision": "infra",
    "project_mac_mini_runner_reauth": "infra",
    "success_autonomous-infra-diagnosis": "infra",
    "success_infrastructure-deploy-verify-document-au": "infra",
    "success_daemon-deadlock-diagnosis-deploy": "infra",
    "success_fast_diagnosis_to_push": "infra",
    "success_verify-prod-deployment-state": "infra",
    "success_autonomous-recovery-restart-and-verify": "infra",
    "success_fast_cache_root_cause": "infra",
    "success_autonomous-core-infra-fix-complete-shipp": "infra",

    # === scraper (scraper, product data, SalesHub, extraction, browser automation) ===
    "feedback_audit_scraper_data": "scraper",
    "feedback_enrich_everything_no_filters": "scraper",
    "feedback_scraper_runs_on_host_not_hero": "scraper",
    "feedback_screenshots_are_source_of_truth": "scraper",
    "feedback_no_supportable": "scraper",
    "feedback_quality_gate_on_every_extraction": "scraper",
    "feedback_preflight_signal_refresh": "scraper",
    "feedback_daily_brief_customer_filter": "scraper",
    "feedback_page_text_drives_extraction": "scraper",
    "feedback_respect-confidential-content-markings": "scraper",
    "feedback_rh-portal-account-search-full-legal-name": "scraper",
    "feedback_bootstrap-preserves-auth-tokens": "scraper",
    "feedback_bootstrap-respects-pod-selection": "scraper",
    "feedback_cases_are_l3_not_l4": "scraper",
    "feedback_iframe-aware-scraper-queries": "scraper",
    "feedback_read_architecture_before_scraper": "scraper",
    "feedback_scraper-worker-context-lifecycle": "scraper",
    "feedback_scraper_iterate_until_zero_gaps": "scraper",
    "feedback_screenshot_is_source_of_truth": "scraper",
    "feedback_visual_scan_before_scrape": "scraper",
    "feedback_marcus_scraper_scope": "scraper",
    "feedback_validate-dom-before-trusting-status": "scraper",
    "feedback_page-fill-during-unstable-states": "scraper",
    "feedback_page-route-predicate-over-glob": "scraper",
    "project_phase3_signal_intelligence": "scraper",
    "project_segment_field_collision": "scraper",
    "project_saleshub_integration": "scraper",
    "project_sf_bookings_architecture": "scraper",
    "project_browser_tab_leak_mac_mini": "scraper",
    "project_ecosystem_catalog_api": "scraper",
    "project_integrations_cross_reference": "scraper",
    "project_rh_discovery_api": "scraper",
    "project_seismic_library_api": "scraper",
    "project_sf_report_browser": "scraper",
    "success_email_extract_campaign_pipeline": "scraper",
    "success_external_domain_http_fetch": "scraper",

    # === process (dev loop, ship workflow, worktree, audit, git protocol) ===
    "feedback_audit_before_presenting": "process",
    "feedback_audit_validate_before_push": "process",
    "feedback_before_after_audit_pattern": "process",
    "feedback_claude_md_gate": "process",
    "feedback_clear_hints": "process",
    "feedback_deployment-pipeline-sequence": "deployment",
    "feedback_dev-loop-tests-docs-mandatory": "process",
    "feedback_dev_loop_autonomous": "process",
    "feedback_dev_loop_urgency_skip": "process",
    "feedback_doc_metadata_on_every_edit": "delivery",
    "feedback_gates_before_commit": "process",
    "feedback_iterative_output_review": "process",
    "feedback_iterative_quality_loop": "process",
    "feedback_mandatory-dev-loop": "process",
    "feedback_never_ask_at_action_boundaries": "process",
    "feedback_new_project_workflow": "process",
    "feedback_parallel_agents_while_building": "delegation",
    "feedback_project_state_live_updates": "process",
    "feedback_scope_check_agent_diffs": "process",
    "feedback_security_scan_testing_loop": "security",
    "feedback_worktree_file_overwrite_guard": "process",
    "feedback_worktree_isolation": "process",
    "feedback_worktree_merge_hygiene": "process",
    "feedback_avoid-unnecessary-doc-regeneration": "delivery",
    "feedback_linkedin_spec_gate": "delivery",
    "feedback_audit_before_fixing": "process",
    "feedback_checkpoint_before_scope_expansion": "process",
    "feedback_diagnostic_loop_working": "process",
    "feedback_execution_discipline": "process",
    "feedback_mechanical_enforcement_over_rules": "process",
    "feedback_resume-session-verify-state": "process",
    "feedback_structured_approval_pattern": "process",
    "feedback_batch_afk_pattern_validated": "delegation",
    "feedback_batch_processing_velocity": "delegation",
    "feedback_commit_after_every_working_change": "process",
    "feedback_convergence_loop_all_items": "process",
    "feedback_forced_disposition_audits": "process",
    "feedback_post_findings_to_issues": "delivery",
    "feedback_spec_doc_gate_mechanical": "delivery",
    "feedback_template_read_before_write": "delivery",
    "feedback_test_before_scaling": "testing",
    "feedback_worktree_merge_strategy": "process",
    "feedback_session_recap_format": "process",
    "feedback_read-background-task-output": "process",
    "feedback_marcus_git_protocol": "infra",
    "feedback_no_questions_during_afk_harness": "delegation",
    "feedback_ac_garbage_test": "testing",
    "feedback_acs_must_include_call_site": "testing",
    "feedback_close_and_document_without_prompting": "delivery",
    "feedback_doc_cascade_on_ship": "delivery",
    "feedback_docs_always_current": "delivery",
    "feedback_grill_logs_findings_as_issues": "delivery",
    "feedback_manual_targeted_over_workflow": "scope",
    "feedback_no_pause_on_discovered_gaps": "scope",
    "feedback_ship_posts_acs_to_issue": "delivery",
    "feedback_slow_down_regroup": "scope",
    "feedback_zero_test_failures_gate": "testing",
    "feedback_harness_compaction": "architecture",
    "feedback_read_spec_at_every_decision": "scope",
    "steering_one_change_when_debugging": "process",
    "steering_error_recovery": "process",
    "steering_plan_means_stop": "scope",
    "project_harness_standard_vision": "process",
    "success_afk_parallel_marathon": "delegation",
    "success_gate_system_build": "process",
    "success_council_audit_fix_loop": "delivery",
    "success_master_sheet_drop_zone": "process",
    "success_screenshot_to_shipped_flow": "process",
    "success_ship_all_findings_council_loop": "delivery",
    "success_systematic_audit_then_enforce": "delivery",
    "success_zero-failures-persistence": "testing",
    "success_explicit-multi-agent-workflow-confirmati": "delegation",
    "success_backlog-template-single-source-of-truth": "process",
    "success_decision-threshold-proposal-with-example": "process",
    "success_harness_driven_loop": "process",
    "success_pre_investigate_then_ship": "process",
    "success_research_then_update_flow": "process",
    "success_slide_deck_as_requirements_source": "process",
    "success_autonomous-backlog-execution": "delegation",
    "success_afk_batch_with_durability": "delegation",
    "success_structured-backlog-driven-session": "delivery",

    # === deployment (general deploy context, projects) ===
    "feedback_always_ask_can_we_test": "deployment",
    "feedback_consumer_output_gate": "deployment",
    "feedback_council_audit_validates_design": "deployment",
    "feedback_thinking_budget": "deployment",
    "project_account_team_contract": "deployment",
    "project_agentgrit_migration": "deployment",
    "project_public_issue_workflow": "deployment",
    "project_adr030_inputs": "deployment",
    "project_quality_gate_pattern": "deployment",
    "project_public_repo_no_source": "deployment",
    "project_ddb_sanitization_remediation": "deployment",
    "Brief and dashboard must render consistently (from debrief 2026-06-11)": "deployment",
    "feedback_no_gemini_api": "deployment",
    "feedback_sse-mock-ci-rest-fallback-required": "deployment",

    # === testing (test practices, TDD, verification, diagnosis) ===
    "feedback_unit_test_gate": "testing",
    "feedback_run_new_specs_against_test_first": "testing",
    "feedback_rerun-tests-after-fix": "testing",
    "feedback_testing_new_user": "testing",
    "feedback_test-first-deployment-verification": "testing",
    "feedback_mid_session_ship_enforcement": "testing",
    "feedback_verify-deployment-before-claiming-shipped": "testing",
    "feedback_da_must_verify_before_closing": "testing",
    "feedback_verify-performance-claims-mechanism": "testing",
    "feedback_verify-state-matches-conversation-context": "testing",
    "feedback_verify-prerequisites-before-assessing-feasibility": "testing",
    "feedback_verify_before_answering": "testing",
    "feedback_verify_before_asking": "testing",
    "feedback_proactive-spot-check-patterns": "testing",
    "feedback_exhaustive-search-before-claiming-nonexistence": "testing",
    "feedback_investigate_logs_before_assumptions": "testing",
    "feedback_verify-tool-capabilities-before-workarounds": "testing",
    "feedback_diagnose-from-git-diff-not-commit-message": "testing",
    "feedback_e2e_data_flow_test": "testing",
    "feedback_fast_root_cause_tracing": "testing",
    "feedback_verify_architecture_against_code": "testing",
    "feedback_verify_data_sources_before_claiming_empty": "testing",
    "feedback_verify_rendered_gdoc_output": "testing",
    "feedback_verify-complete-message-delivery": "testing",
    "feedback_verify-live-dashboard-display-before-describing": "testing",
    "feedback_smoke_test_pipelines": "testing",
    "feedback_reevaluation_gate_after_shipping": "testing",
    "feedback_signal_to_output_trace": "testing",
    "feedback_validate_against_spec_not_own_data": "testing",
    "steering_never_assert_without_verification": "testing",
    "success_acceptance-criteria-verification-clarify": "testing",
    "success_example-table-data-validation": "testing",
    "success_systematic-format-standardization-verifi": "testing",
    "success_systematic-removal-with-verification": "testing",
    "success_ci-automation-verify-test-results": "testing",
    "success_ci_watch_through_to_green": "testing",
    "success_verify-data-state-diagnose-root-cause": "testing",
    "success_adversarial_e2e_testing": "testing",
    "success_adversarial_parity_audit": "testing",

    # === ui (Quinn, Playwright, visual, UX) ===
    "feedback_comprehensive-visual-audit-during-analysis": "ui",
    "feedback_condition-driven-waits-browser-automation": "ui",
    "feedback_quinn_must_verify_data_quality": "ui",
    "feedback_quinn_no_config_wipe": "ui",
    "feedback_quinn_visual_standards": "ui",
    "feedback_trace_all_render_sites": "ui",
    "feedback_verify_rendered_ui_not_just_code": "ui",
    "feedback_quinn_after_every_ui_commit": "ui",
    "feedback_quinn_before_image_tag": "ui",
    "feedback_quinn_before_presenting": "ui",
    "feedback_quinn_gate_in_batch_mode": "ui",
    "feedback_live_ui_verification_required": "ui",
    "feedback_ui_reviewer_post_rebuild": "ui",
    "feedback_ux_visual_review_before_quinn": "ui",
    "feedback_reuse_components_not_copy": "ui",
    "feedback_ux_frictionless": "ui",
    "success_visual_inventory_checklist": "ui",
    "success_ui-pattern-consistency-smart-defaults": "ui",

    # === scope ===
    "feedback_articulate-requests-clearly": "scope",
    "feedback_build_toward_deal_outcomes": "scope",
    "feedback_complete-thoughts-before-confirming": "scope",
    "feedback_dialog_and_questions": "scope",
    "feedback_match_question_scope": "scope",
    "feedback_goal_statement_before_shipping": "scope",
    "feedback_ask_before_removing_features": "scope",
    "feedback_wrong-scope-answered-misreading-jasons-intent-5-oc": "scope",
    "feedback_source-context-evidence-weight": "scope",
    "feedback_structured-code-exploration-with-triage": "scope",
    "feedback_avoid-minimal-single-word-responses": "scope",
    "feedback_consolidate-corrections-before-stating": "scope",
    "feedback_intent-clarification-post-context-break": "scope",
    "feedback_respect-wait-pause-user-signal": "scope",
    "feedback_pai_not_jasons_project": "scope",
    "feedback_portability_check": "scope",
    "steering_askuserquestion_for_choices": "scope",
    "steering_dont_modify_user_content": "scope",
    "steering_identity_first_person": "scope",
    "steering_minimal_scope": "scope",
    "success_technical-explanation-direct-and-structu": "scope",

    # === delivery (shipping, docs, completion, content) ===
    "feedback_docs_always_updated": "delivery",
    "feedback_durability_gate_before_continuing": "delivery",
    "feedback_every_issue_through_ship": "delivery",
    "feedback_never_bypass_ship_scope": "delivery",
    "feedback_read_templates_before_acs": "delivery",
    "feedback_template_compliance_live": "delivery",
    "feedback_inspect_consumer_output": "delivery",
    "feedback_research_before_designing": "delivery",
    "feedback_deterministic_over_gemini": "delivery",
    "feedback_preserve-all-form-object-properties": "delivery",
    "feedback_use-serena-template-not-freeform": "delivery",
    "feedback_clarify_before_documenting": "delivery",
    "feedback_daily-brief-pipeline-intelligence-focus": "delivery",
    "feedback_no_false_completions": "delivery",
    "feedback_incomplete-delivery-presented-as-complete-4-occurr": "delivery",
    "feedback_spec_fidelity_gap": "delivery",
    "feedback_update_gdoc_in_place": "delivery",
    "Canonical vocabulary for shared constants (from debrief 2026-06-24)": "delivery",
    "project_backlog_verified_state": "delivery",
    "project_content_campaign": "delivery",
    "project_linkedin_content_strategy": "delivery",
    "success_council-audit-consumer-contract-loop": "delivery",
    "success_runbook_durability_chain": "delivery",
    "success_4_layer_consumer_verification": "delivery",
    "success_comprehensive_council_audit": "delivery",
    "success_council_audit_loop": "escalation",
    "success_council_audit_loop_to_A": "escalation",
    "success_council_driven_quality_hillclimb": "escalation",
    "success_grill_ship_council_loop": "delivery",
    "success_spec_driven_generated_outputs": "delivery",
    "success_html_export_hyperlinks": "delivery",
    "success_hill_climbing_prompt_optimization": "algorithm",

    # === delegation ===
    "feedback_agent_model_routing": "delegation",
    "feedback_delegate_code_changes": "delegation",
    "feedback_pre-brief-agent-scope-constraints": "delegation",
    "feedback_proactive_agents": "delegation",
    "feedback_wait-for-agent-findings-before-synthesis": "delegation",
    "feedback_marcus_opus_for_structural": "delegation",
    "feedback_research_before_advising": "delegation",
    "feedback_synthesize_silently": "delegation",
    "feedback_delegate_more": "delegation",
    "feedback_escalate_early": "delegation",
    "feedback_bypass_permissions_all_agents": "delegation",
    "feedback_no_escape_hatches_in_briefs": "delegation",
    "feedback_research_before_implement": "delegation",
    "feedback_model_selection_judgment": "delegation",
    "feedback_sonnet_for_execution": "delegation",
    "feedback_token_efficiency": "delegation",
    "steering_always_use_named_agents": "delegation",
    "success_council_then_research_then_ship": "delegation",

    # === architecture ===
    "Gate all optional dependencies with dynamic import (from debrief 2026-06-12)": "architecture",
    "feedback_projects_outside_claude": "architecture",
    "feedback_project_guardrails_template": "architecture",
    "feedback_temporary-becomes-permanent": "architecture",
    "feedback_architecture_in_mandatory_read_path": "architecture",
    "feedback_design_complete_before_building": "architecture",
    "feedback_design_for_least_complexity": "architecture",
    "feedback_interactive_architecture_discovery": "architecture",
    "feedback_council_before_architecture": "architecture",
    "feedback_council_plus_context7": "architecture",
    "feedback_council_right_question_first": "architecture",
    "feedback_context7_before_guessing": "architecture",
    "feedback_project_bootstrap_doc": "architecture",
    "project_compounding_skills_design": "architecture",
    "project_smart_rule_injection": "architecture",
    "project_workflow_conversion": "architecture",
    "project_agentgrit": "architecture",
    "project_contract_compliance_before_graph": "architecture",
    "project_intelligence_engine_9_pillars": "architecture",
    "project_unified_harness_output_types": "architecture",
    "project_workflow_trust_investigation": "architecture",
    "project_harness_agentbrain_gaps": "architecture",
    "project_skill_optimizer_workflow": "architecture",
    "project_architecture_drift_council": "architecture",
    "project_doc_architecture_design": "architecture",
    "project_intelligence_graph_vision": "architecture",
    "project_signal_index_architecture": "architecture",
    "project_unified_ship_workflow": "architecture",
    "project_generic_optimizer": "architecture",
    "project_universal_e2e_verify": "architecture",
    "steering_pai_inference_tool_for_ai_calls": "architecture",
    "steering_first_principles_over_bolt_ons": "architecture",
    "steering_read_before_modifying": "architecture",
    "success_lean-agent-knowledge-architecture": "architecture",
    "success_design_before_build_agentgrit": "architecture",
    "success_architecture_clarity_session": "architecture",
    "success_build_diagnostic_then_fix": "architecture",
    "success_audit_then_architecture_then_ship": "architecture",
    "success_architecture-to-backlog-flow": "architecture",
    "success_research_grill_build_iterate": "architecture",
    "success_signal-architecture-overhaul": "architecture",

    # === memory ===
    "feedback_capture_decisions_immediately": "memory",
    "feedback_no_notion": "memory",
    "feedback_auto_log_backlog": "memory",
    "feedback_log_all_findings_immediately": "memory",
    "feedback_mechanicals_over_memory": "memory",
    "feedback_algorithm_learn_backlog_promotion": "memory",
    "project_memory_loop": "memory",
    "project_model_doc_experiment": "memory",

    # === algorithm ===
    "project_pai_backlog": "algorithm",
    "project_campaign_quality_upgrade": "algorithm",
    "project_meeting_prep_skill": "algorithm",
    "project_meeting_prep_intelligence": "algorithm",
    "feedback_measure_before_optimizing": "algorithm",
    "feedback_root_cause_data_first": "algorithm",
    "feedback_flag_rule_conflicts": "algorithm",
    "steering_build_isc_from_every_request": "algorithm",

    # === data ===
    "feedback_territory_sheet_lifecycle": "data",
    "feedback_track-gemini-model-versions": "data",
    "project_codebase_optimization": "data",
    "project_control_plane_vision": "data",
    "project_pai_vault": "data",
    "project_customer_intelligence": "data",
    "project_proactive_engagement_intelligence": "data",
    "project_proactive_intelligence_vision": "data",
    "project_application_mission": "data",
    "success_data-analysis-timeline-expectations": "data",
    "success_real-data-honest-gaps": "data",
    "success_context_audit_walkthrough": "data",
    "feedback_backlog-verify-before-presenting": "data",

    # === escalation ===
    "success_structured-technical-plan-with-dependenc": "escalation",
    "success_structured-design-walkthrough-for-approv": "escalation",
    "success_council_diagnose_ship_deploy": "escalation",
    "success_council_for_risky_remediation": "escalation",
    "success_council_found_dead_pipeline": "escalation",
    "feedback_worktree_merge_coordination": "escalation",

    # === browser ===
    "reference_rh_portal_login": "browser",
    "reference_salesforce": "browser",
    "reference_gdrive_write_scope": "browser",
    "reference_hydra_search_api": "browser",
    "feedback_read_project_docs_at_session_start": "browser",
    "feedback_read_project_docs_before_investigating": "browser",

    # === security ===
    "feedback_no_auth": "security",
    "feedback_rook_no_destructive_tests": "security",
    "feedback_security_review_architecture_first": "security",
    "steering_ask_before_destructive_actions": "security",
    "steering_check_git_remote_before_push": "security",
    "feedback_verify_before_ops": "security",

    # remaining
    "feedback_capture-incomplete-no-learning-section": "memory",
    "feedback_incomplete-capture-cannot-extract-lesson": "memory",
    "feedback_incomplete-capture-cannot-process": "memory",
    "user_role": "scope",
    "success_comp_tracker_skill": "delivery",
    "success_comparative-positioning-honest-gaps": "delivery",
    "success_direct-solution-with-reasoning-when-clea": "scope",
    "success_guard-first-thinking": "architecture",
    "success_urgent-minimal-solution-with-future-extr": "scope",
    "success_context7-doc-lookup-pattern": "architecture",
    "success_context7_api_discovery": "architecture",
    "success_diagnosis_first_pipeline_fix": "testing",
    "success_cross_layer_consistency_audit": "testing",
    "project_council_iteration_value": "delivery",
    "project_dailybrief_gap_backlog": "delivery",
    "feedback_council_email_rules": "delivery",
    "feedback_council_parallel_agents_real_data_audit": "delegation",
    "feedback_verify-live-dashboard-display-before-describing": "testing",
    "feedback_always_update_docs": "delivery",
    "steering_surgical_fixes_only": "scope",
    "success_interactive_gate_design": "delivery",
}


def main():
    kg = json.loads(KG_PATH.read_text())
    nodes = kg["nodes"]

    rules = {}
    missing = []
    for nid in nodes:
        if nid in EXPLICIT:
            rules[nid] = {"domains": [EXPLICIT[nid]], "source": "auto"}
        else:
            missing.append(nid)

    if missing:
        print(f"UNCLASSIFIED ({len(missing)}):")
        for nid in sorted(missing):
            desc = nodes[nid].get("description", "")[:80]
            print(f"  {nid}: {desc}")
        print("\nNot writing — classify these first.")
        return

    domain_counts = Counter()
    for entry in rules.values():
        for d in entry["domains"]:
            domain_counts[d] += 1

    total = len(rules)
    print(f"Total: {total}")
    violations = []
    print(f"\nDomain distribution ({len(domain_counts)} domains):")
    for d, cnt in domain_counts.most_common():
        flag = ""
        if cnt > 50:
            flag = " *** OVER 50"
            violations.append(f"{d}={cnt}")
        if cnt < 3:
            flag = " *** UNDER 3"
            violations.append(f"{d}={cnt}")
        print(f"  {d}: {cnt}{flag}")

    if violations:
        print(f"\nVIOLATIONS: {violations}")
        print("Not writing.")
    else:
        rd = {"version": 1, "reviewed": True, "rules": rules}
        RD_PATH.write_text(json.dumps(rd, indent=2) + "\n")
        print(f"\nAll constraints satisfied! Wrote {RD_PATH}")


if __name__ == "__main__":
    main()
